### ISSUE TITLE
What is this repository for? Please write a basic README with a progress report

### ISSUE THREAD

**Issue by ibnIrshad** [OpenExoplanetCatalogue/oec_external#1]
It seems like this repository is doing some of the work which you hoped that we, CSCC01 students, would build for our OEC updater project. Is that true? If I understand it correctly, this oec_external repo contains code to read external databases and generate XML that can then be used to compare with OEC data. 

I can see this code becoming massively useful in our projects. Since you have the expertise to understand and parse the external database, it would probably be easier for you to write this parser component yourself, rather than communicating with 20+ other teams trying to understand the same thing (how to interpret the data from external dbs). We could then use this parsing component in our final software. 

However in order for this to work out, we need to communicate to figure out a common API for packaging, versioning, and implementing this parser component within our larger projects. It won't be difficult, and I hope to talk to you soon in person about it. Until then, it would be helpful to have a README for this repository with a basic statement of intent and progress report (is the EU database parsing ready yet)?

**Comment by hannorein** [comment]
Please ignore this repository. If you can extract something useful, go ahead, but this should not be the basis of your work for cscc01.
